/** Catalogue types and URL shapes. No Node imports — the tiles use this too. */

/**
 * The bundle ships every image twice and picks a set at boot: phones get
 * `@0.5x`, tablets and desktops `@1x`. Slice paths therefore carry a `{tier}`
 * placeholder rather than a folder, because prefetching the tier the game will
 * not ask for caches bytes nobody reads and competes with the ones it will.
 */
export const TIERS = ['@1x', '@0.5x'] as const;
export type AssetTier = (typeof TIERS)[number];

export const TIER_TOKEN = '{tier}';

export function isAssetTier(value: unknown): value is AssetTier {
  return TIERS.includes(value as AssetTier);
}

/** Resolves a slice path against a tier. Paths without the token pass through. */
export function resolveTier(path: string, tier: AssetTier): string {
  return path.split(TIER_TOKEN).join(tier);
}

/**
 * The bundle hands Howler `[ogg, mp3]` and Howler takes the first format the
 * browser reports it can decode, so the choice is the browser's, not ours.
 * Audio paths carry a `{fmt}` placeholder for the same reason slice paths carry
 * `{tier}`: caching the format the game will not ask for spends a player's
 * bandwidth on bytes nothing ever decodes.
 */
export const AUDIO_FORMATS = ['ogg', 'mp3'] as const;
export type AudioFormat = (typeof AUDIO_FORMATS)[number];

export const FMT_TOKEN = '{fmt}';

export function isAudioFormat(value: unknown): value is AudioFormat {
  return AUDIO_FORMATS.includes(value as AudioFormat);
}

/** Resolves an audio path against a format. The token appears in both the folder and the extension. */
export function resolveFormat(path: string, format: AudioFormat): string {
  return path.split(FMT_TOKEN).join(format);
}

/** `bytes` is the larger variant — `@1x` for a tier, ogg for a format — so it is an upper bound. */
export type SliceAsset = { path: string; bytes: number };

/** Presentation only. Every game boots the same bundle; the gradient and symbol are what differ. */
export type Game = {
  slug: string;
  name: string;
  provider: string;
  symbol: string;
  gradient: string;
};

export type Catalogue = {
  /** Content hash of the whole bundle. It is in every asset URL, so a URL never changes meaning. */
  bundleVersion: string;
  /** The files needed to reach the Play screen, largest first. Tiered paths carry `{tier}`. */
  slice: SliceAsset[];
  /**
   * The sound worth warming on the lobby, in the order the bundle asks for it —
   * the engine's `soundFiles` then its `lazySoundFiles`, which despite the name
   * are all requested during boot too, 16.6 MB of ogg in total.
   *
   * That is every sound but `FBGM`: the free-spins loop is 5.9 MB, and most
   * sessions never reach the bonus round, so the lobby does not pay for it up
   * front. The worker still caches it when the game fetches it.
   *
   * Prefetched after the slice, never with it. None of it gates the Play
   * screen, so warming it early would spend the very bandwidth the slice needs
   * on bytes no player is waiting for. Paths carry `{fmt}`.
   */
  audio: SliceAsset[];
  /**
   * Everything else in the bundle — the spines behind the reels, the pay table,
   * the `FBGM` loop the audio list leaves out. Defined as a remainder, so it is
   * generated by `scripts/build-rest.mjs` rather than written by hand, and
   * `check:bundle` verifies that slice, audio and rest partition the files on
   * disk. That partition is what lets the worker treat this as *full*.
   *
   * Prefetched last and only for a player who has opened games before: it is
   * 38.8 MB against the 17.5 MB of the two lists above, and a visitor with no
   * history opens a game in 4.5% of sessions. See `lib/recent.ts`. Paths carry
   * both `{tier}` and `{fmt}`.
   */
  rest: SliceAsset[];
  games: Game[];
};

export function assetUrl(bundleVersion: string, path: string): string {
  return `/cdn/${bundleVersion}/${path}`;
}
